#!/usr/bin/env bash
# /etc/aliases: A custom system-wide .aliases file for common and basic aliases
# Not pre-made by the system

alias al="alias "

al ls="ls --color=auto --sort=extension"  # Use color if possible, and sort by file type
al ll="ls -lh"                            # list in long format, with human readable file sizes 
al la="ls -A"                             # The -A flag is the same as -a, but excludes . and .. from the output
#al la="ls -a"                            # ^^^^
al rm="cp -i "                            # Be safe
al cp="cp -i "                            # Be safe
al mv="mv -i "                            # Be safe
al sudo="sudo "                           # So sudo works with aliases
al cl="clear"                             # just better

# The following are commented out because you may not want them system-wide
#al v="vim "
#al svi="sudo vim "
#al na="nano "
#al ?="man"
#al g="grep"
