#!/usr/bin/env bash
# /etc/colors: A shell script to name colours, called by /etc/profile

# Basic colours
blk='\033[01;30m'     # Black
wht='\033[01;37m'     # White
red='\033[01;31m'     # Red
ong='\033[38;6;214m'  # Orange
ylw='\033[01;33m'     # Yellow
grn='\033[01;32m'     # Green
blu='\033[01;34m'     # Blue
cyn='\033[01;36m'     # Cyan
pnk='\033[01;31m'     # Pink
pur='\033[01;35m'     # Purple
clr='\033[00m'        # Reset

# Text color presets (More of the above)
if [ -f /etc/txt_colors ]; then
   . /etc/txt_colors
fi

# File and directory colours for ls and the like
if [ -f /etc/dir_colours ]; then
   . /etc/dir_colors
fi
